test("first test", () => {
  throw new Error("something failed");
});
